# If platform config/runner not specified on a command line, use reference python runner to run this MLBox on a
# local machine using python environment.
implementation_type: docker

image: mlperf/mlbox-hello-world

docker_runtime: docker

configure: build

docker_args: []

command: []

args: []
